# Server Configuration
server:
  port: 8081

# Kafka Configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: appointment_service_group
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Logging Configuration
logging:
  level:
    org.springframework.kafka: DEBUG
    com.example.appointmentservice: DEBUG
